# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - "release/**"
      - "main"
  release:
    types: [ published ]
  pull_request:
    types: [ synchronize,opened,reopened ]
    branches:
      - main
      - "release/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      checks: read
      issues: write
      actions: write
      contents: write
      statuses: write
      deployments: write
      pull-requests: write
      security-events: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 19.0.5
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git
            semantic-release-gitmoji
            @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}